package main

import (
	"fmt"
	queue "lab4/Queue"
)

func main() {
	queArr := queue.NewQueueArray()
	queArr.Push(1)
	queArr.Push(2)
	queArr.Push(3)
	queArr.Push(4)
	queArr.Push(5)
	queArr.Push(6)
	queArr.Push(7)
	queArr.Push(8)
	num := queArr.Get()
	fmt.Println(num)
	num = queArr.Get()
	fmt.Println(num)
	num = queArr.Get()
	fmt.Println(num)
	num = queArr.Get()
	fmt.Println(num)
	num = queArr.Get()
	fmt.Println(num)
	num = queArr.Get()
	fmt.Println(num)
	num = queArr.Get()
	fmt.Println(num)
	num = queArr.Get()
	fmt.Println(num)

	queLL := queue.NewQueueLL()
	queLL.Push(1)
	queLL.Push(2)
	queLL.Push(3)
	queLL.Push(4)
	queLL.Push(5)
	queLL.Push(6)
	queLL.Push(7)
	queLL.Push(8)
	queLL.Push(9)
	num = queLL.Get()
	fmt.Println(num)
	num = queLL.Get()
	fmt.Println(num)
	num = queLL.Get()
	fmt.Println(num)
	num = queLL.Get()
	fmt.Println(num)
	num = queLL.Get()
	fmt.Println(num)
	num = queLL.Get()
	fmt.Println(num)
	num = queLL.Get()
	fmt.Println(num)
	num = queLL.Get()
	fmt.Println(num)
	num = queLL.Get()
	fmt.Println(num)

}
